# Generated by Django 3.1.1 on 2020-10-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
